Merge Request: Integration of Updated Test Code and Test Data from multivariateAnalysisR-testthat to Master
genesofeve/projectR pull request #33
Opened 2023-11-08 17:21 UTC by tlsgusdn1107

This pull request proposes the integration of the enhanced test code and newly created test data from the multivariateAnalysisR-testthat branch into the master branch.

2023-11-10 21:53 UTC, dimalvovs requested changes

2023-11-10 21:53 UTC, dimalvovs commented on data/.Rapp.history
@tlsgusdn1107 do we need this file in the repo at all? sorry if it's obvious!

2023-11-10 21:53 UTC, dimalvovs commented on tests/testthat/test_projectR.R
SeuratObject needs to be added to `Suggests` then.

2023-11-10 22:48 UTC, dimalvovs commented on .github/workflows/R-CMD-check.yml
Do we really want to include this feature branch in Actions? Actions are long-lived and `multivariateAnalysisR-testthat` is short-lived branch. I'd better consider adding `work_dispatch` to run the actions manually, or rely on already existing pre-pull action.

2023-11-11 09:35 UTC, tlsgusdn1107 commented on data/.Rapp.history
No problem! I assume you're referring to `data/multivariateAnalysisR-seurat-test.rds`. The file is needed to test run the multivariateAnalysis() function!

2023-11-11 09:37 UTC, tlsgusdn1107 commented on data/.Rapp.history
I've put `data/multivariateAnalysisR-seurat-test.rds` in `/data` folder because other test data files are also in that folder.

2023-11-11 09:45 UTC, tlsgusdn1107 commented on tests/testthat/test_projectR.R
Added

2023-11-11 10:36 UTC, tlsgusdn1107 commented on .github/workflows/R-CMD-check.yml
Fixed with `work_dispatch` as suggested!

2023-11-11 10:40 UTC, tlsgusdn1107 commented on .github/workflows/R-CMD-check.yml
@dimalvovs need to merge with `master` default branch to see manual trigger button. Would you mind if you could help with that?

2023-11-11 14:26 UTC, dimalvovs commented on .github/workflows/R-CMD-check.yml
since actions is not part of the main codebase I've amended it directly in the master branch

2023-11-11 18:09 UTC, tlsgusdn1107 reviewed
Updated actions to match with `master` branch.

2023-11-11 18:10 UTC, tlsgusdn1107 commented on .github/workflows/R-CMD-check.yml
Great! Made changes to the actions file to match with that of `master` branch. Do you think it's good to merge?

2023-11-15 15:15 UTC, genesofeve commented on .github/workflows/R-CMD-check.yml
can you please modify to pass the R-CMD-check and I will merge?

2023-11-15 17:55 UTC, tlsgusdn1107 commented on .github/workflows/R-CMD-check.yml
@dimalvovs I've made changes as suggested, but the following error pops up. Would you mind if you could give a check and let me know what you'd suggest to do? Thank you!

❯ checking for missing documentation entries ... WARNING
  Undocumented code objects:
    ‘multivariateAnalysisR_seurat_test’
  Undocumented data sets:
    ‘multivariateAnalysisR_seurat_test’
  All user-level objects in a package should have documentation entries.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

❯ checking LazyData ... WARNING
    LazyData DB of 6.5 MB without LazyDataCompression set
    See §1.1.6 of 'Writing R Extensions'

2023-11-15 18:18 UTC, dimalvovs commented on .github/workflows/R-CMD-check.yml
the data object that you added for test is undocumented. see [example](https://github.com/genesofeve/projectR/blob/multivariateAnalysisR-testthat/R/package.R ) on how to document.

1. could you have used an existing data object to test your output? 
2. do you really need 1.6Mb data object to test your code?
3. is [the is.null(output)](https://github.com/genesofeve/projectR/blob/09208021ac5c9d9de3d4d090dce60410e283fcea/tests/testthat/test_projectR.R#L55C2-L55C30) only functionality that your code brings? lets consider a more real life test, for example how did you test that your function works?

2023-11-15 23:00 UTC, tlsgusdn1107 commented on .github/workflows/R-CMD-check.yml
1. no, the function is specifically for Seurat Obj with data in @meta.data, which only `multivariateAnalysisR-seurat-test` data has
2. i could truncate the # of observations in the `multivariateAnalysisR-seurat-test` data to further reduce the file size
3. multivariateAnalysisR function only exports w/o return, so i'll modify it to return some intermediate results then.

2023-11-15 23:49 UTC, tlsgusdn1107 commented on .github/workflows/R-CMD-check.yml
updates 
1 & 2: truncated to 990KB data
3: added couple more expect_XX

2023-11-16 01:18 UTC, tlsgusdn1107 commented on .github/workflows/R-CMD-check.yml
@dimalvovs no errors with multivariateAnalysisR now (i believe). Actions log shows the following errors (i think we talked about the first one in Slack):

❯ checking for missing documentation entries ... WARNING
  Warning: replacing previous import ‘S4Arrays::makeNindexFromArrayViewport’ by ‘DelayedArray::makeNindexFromArrayViewport’ when loading ‘SummarizedExperiment’
  All user-level objects in a package should have documentation entries.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

❯ checking LazyData ... WARNING
    LazyData DB of 5.6 MB without LazyDataCompression set
    See §1.1.6 of 'Writing R Extensions'

2023-11-21 19:28 UTC, dimalvovs commented on .github/workflows/R-CMD-check.yml
@tlsgusdn1107 hi, thanks for updates!
1. I think that this check:
❯ checking for missing documentation entries ... WARNING
 actually generates the following result we need to take care:
"All user-level objects in a package should have documentation entries.", basically it is reacting to the undocumented dataset that you added.

2023-11-27 10:24 UTC, ceruleane commented on .github/workflows/R-CMD-check.yml
@dimalvovs All documentations should be covered. I recall the same error log showing up b4 adding a new dataset for testing multivariateAnalysisR function. If I misunderstood the issue, would you mind if you could help guide me what to fix?

LazyData WARNING is also stopping the package from being checked.

2023-11-28 15:03 UTC, dimalvovs commented on .github/workflows/R-CMD-check.yml
Great, thank you for fixing the docs!  The last warning left - the one about LazyData. Bioconductor advices (2.7) not to use lazyData=TRUE but does not deny it. Since the current bioc version has LazyData=TRUE I suggest we keep it as is. 
As regards to the warning itself, it can be avoided by adding `LazyDataCompression: gzip` to the DESCRIPTION. We can discuss this.

2023-11-28 22:21 UTC, tlsgusdn1107 commented on .github/workflows/R-CMD-check.yml
@dimalvovs the docs were not fixed; all docs already had the data documented, but the error persists. would you mind if you could take a look into that?

I'll add the line to description soon.

2023-11-30 14:50 UTC, tlsgusdn1107 commented on .github/workflows/R-CMD-check.yml
Description not edited since workflow passed for all three machines.

2023-11-30 14:53 UTC, tlsgusdn1107 commented
@dimalvovs @genesofeve final check to merge.

1. version num in DESCRIPTION file can be updated to the master one to resolve conflicts.
2. Github Workflow passes for the requested branch.

2023-12-01 18:57 UTC, merged